### ISSUE TITLE
[issue] 200MB too fat

### ISSUE THREAD

**Issue by SiddharthSharma16923** [jenius-apps/ambie#285]
is it true that appx packages of same apps are just fat 
example is ode okular (its just fat in appx format ) , the 7z sideload release is thin af (300 vs 80 MB)

**Comment by SiddharthSharma16923** [comment]
*kde okular

**Comment by dpaulino** [comment]
Are you referring to Ambie's 200MB msixbundle files on GitHub? This isn't Ambie's true size.

Ambie's true size is about 70MB. The reason you see 200 MB for its msixbundle is because that msixbundle file is a collection of 3 different copies of Ambie: a copy for x86, a copy for x64, and a copy for ARM64. 

If you download Ambie from the Microsoft Store (which is the recommended acquisition process), Windows will automatically download only the 70MB copy that works on your machine, so you wouldn't download the full 200MB msixbundle file. 

If you download the file from GitHub, it isn't smart enough to determine which bundle to download, so you just download the entire file.

Please download Ambie from the Microsoft Store instead if you are concerned about download size.
