### ISSUE TITLE
[Request] for easier localization

### ISSUE THREAD

**Issue by KristofKekesi** [jenius-apps/ambie#61]
## Hello devs!

For [Files](https://github.com/files-community/Files) I put my translation into a [.xlf file](https://github.com/files-community/Files/tree/master/Files/MultilingualResources). It is more useful so I would be glad if you would add this feature.
Hungarian is caotic in its way, so google translate is doing more harm than good. I check Ambie every second day so hungarian is always up to date.

Thanks for your consideration.

**Comment by dpaulino** [comment]
I'm new to localization so this feedback is very valuable, thank you! I will investigate the xlf file soon!

**Comment by dpaulino** [comment]
@KristofKekesi thanks again for this suggestion. I have enabled xlf files in ambie, however, I did not create xlf files yet for the existing languages. I noticed that doing so will delete the existing translations, and I didn't want to move all the languages in one sitting from resw to xlf (and because I am sure I would have made errors). 

If you have time, please feel free to move the Hungarian resw to an xlf! I really appreciate your contributions!

**Comment by dpaulino** [comment]
Actually, please hold off on that! It seems there is a way to convert our existing resw files into xlf files. I set up a task to do this work #78
